project:
  type: book
  output-dir: docs

book:
  title: "Shiny Getting Started"
  author: "Mine Çetinkaya-Rundel"
  date: "2/25/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Hello Shiny"
      chapters:
        - hello.qmd
        - hello-ui.qmd
        - hello-server.qmd
        - hello-recap.qmd
    - part: flow.qmd
    - part: reactivity.qmd
    - part: ui.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

