project:
  type: book
  output-dir: docs

book:
  title: "Shiny Getting Started"
  author: "Mine Çetinkaya-Rundel"
  date: "2/25/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - hello.qmd
    - flow.qmd
    - reactivity.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

