name: Deploy Quarto book

on:
  push:
    branches: main
  pull_request:
    branches: main
  # to be able to trigger a manual build
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v2
#      - with:
#	 persist-credentials: false

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/install-quarto@v1
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 
          # uncomment below and fill to pin a version
          # version: 0.9.105

      - name: Render book to all formats
        # Add any command line argument needed
        run: |
          quarto render

      - name: Deploy 
        # only deploy when pushed to main
        # if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # The branch the action should deploy to.
          branch: gh-pages
          # The folder the action should deploy. Adapt if you changed in Quarto config
          folder: docs
